exports.TILES = TILES =
  VOID: 0
  FLOOR: 1
  WALL: 2
  CORRIDOR: 3
  DOOR: 4
  STAIRCASE_UP: 8
  STAIRCASE_DOWN: 9

exports.WALKABLE_TILES = WALKABLE_TILES = {}
WALKABLE_TILES[TILES.FLOOR] = true
WALKABLE_TILES[TILES.CORRIDOR] = true
WALKABLE_TILES[TILES.DOOR] = true
WALKABLE_TILES[TILES.STAIRCASE_UP] = true
WALKABLE_TILES[TILES.STAIRCASE_DOWN] = true
