exports.TILES = TILES =
  VOID: 0
  FLOOR: 1
  WALL: 2
  CORRIDOR: 3
  DOOR: 4
  STAIRCASE_UP: 8
  STAIRCASE_DOWN: 9

exports.WALKABLE_TILES = WALKABLE_TILES = {}
WALKABLE_TILES[TILES.FLOOR] = true
WALKABLE_TILES[TILES.CORRIDOR] = true
WALKABLE_TILES[TILES.DOOR] = true
WALKABLE_TILES[TILES.STAIRCASE_UP] = true
WALKABLE_TILES[TILES.STAIRCASE_DOWN] = true

exports.DIR_TO_VEC = DIR_TO_VEC =
  n: [0, -1]
  s: [0, 1]
  e: [1, 0]
  w: [-1, 0]
  nw: [-1, -1]
  sw: [-1, 1]
  ne: [1, -1]
  se: [1, 1]

exports.ZERO = ZERO = [0, 0]
